services:
  broker:
    build:
      context: "./"
      dockerfile: "./broker/Dockerfile"
    image: "broker:v1"
    container_name: "broker"
    ports:
      - "8080:8080"
    networks:
        - internet
  
  entity:
    build:
      context: "./"
      dockerfile: "./entity/Dockerfile"
    image: "entity:v1"
    tty: true
    stdin_open: true
    networks:
        - internet

networks:
  internet: 
